import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'node:path'

// Wails serves frontend/dist from the embedded filesystem in a production
// build, and proxies to this dev server during `wails dev`.
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
      // Generated Go bindings. Regenerated by wails on every build — never edited.
      '@wails': path.resolve(__dirname, 'wailsjs'),
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // The app never loads anything from the network at run time: it must work
    // on a disconnected machine (spec §2). Everything is bundled.
    assetsInlineLimit: 0,
  },
})
