//go:build integration

// Integration tests against a real PostgreSQL server (spec §16).
//
// Deviation from the spec, deliberate: the spec names testcontainers-go, which
// would pull a large dependency tree into a project that otherwise has eight
// direct dependencies, and would still require Docker at run time. These tests
// take the connection string instead, so they run against a container the
// developer started, a scratch database, or CI's service container — with no
// dependency at all:
//
//	docker run --rm -e POSTGRES_PASSWORD=pgsheet -p 5432:5432 -d postgres:16
//	PGSHEET_TEST_DSN="postgres://postgres:pgsheet@localhost:5432/postgres" \
//	  go test -tags=integration ./...
//
// Without PGSHEET_TEST_DSN every test here skips, so the tagged build stays
// green on a machine with no database.
package introspect_test

import (
	"context"
	"os"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"pgsheet/internal/introspect"
)

// fixtureDDL exercises everything the introspection layer has to get right:
// an identity-always column that must never be mapped, a generated column, a
// serial key with a sequence, an enum, a composite key, a partial unique index
// that cannot be checked offline, and several shapes of CHECK constraint.
const fixtureDDL = `
DROP SCHEMA IF EXISTS pgsheet_test CASCADE;
CREATE SCHEMA pgsheet_test;

CREATE TYPE pgsheet_test.customer_status AS ENUM ('active', 'inactive', 'suspended');

CREATE TABLE pgsheet_test.customers (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref           integer GENERATED ALWAYS AS IDENTITY,
    name          varchar(255) NOT NULL,
    email         varchar(255) NOT NULL UNIQUE,
    phone         varchar(32),
    status        pgsheet_test.customer_status NOT NULL DEFAULT 'active',
    credit_limit  numeric(12,2) DEFAULT 0,
    score         integer,
    code          char(3),
    signup_date   date,
    created_at    timestamptz NOT NULL DEFAULT now(),
    seen_at       timestamp,
    doc           jsonb,
    external_id   uuid,
    active        boolean NOT NULL DEFAULT true,
    ip            inet,
    notes         text,
    display_name  text GENERATED ALWAYS AS (name || ' <' || email || '>') STORED,
    CONSTRAINT customers_score_range CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT customers_credit_positive CHECK (credit_limit >= 0),
    CONSTRAINT customers_email_shape CHECK (email ~ '^[^@]+@[^@]+$'),
    CONSTRAINT customers_code_len CHECK (code IS NULL OR char_length(code) = 3)
);

CREATE UNIQUE INDEX customers_active_phone
    ON pgsheet_test.customers (phone) WHERE active;

CREATE TABLE pgsheet_test.orders (
    customer_id integer NOT NULL REFERENCES pgsheet_test.customers(id),
    line_no     integer NOT NULL,
    amount      numeric(10,2) NOT NULL,
    PRIMARY KEY (customer_id, line_no)
);

CREATE TABLE pgsheet_test.legacy (
    code text PRIMARY KEY,
    label text NOT NULL
);
`

// Pool connects to the test database, or skips.
func Pool(t *testing.T) *pgxpool.Pool {
	t.Helper()

	dsn := os.Getenv("PGSHEET_TEST_DSN")
	if dsn == "" {
		t.Skip("set PGSHEET_TEST_DSN to run the integration tests")
	}

	pool, err := pgxpool.New(context.Background(), dsn)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	t.Cleanup(pool.Close)

	if _, err := pool.Exec(context.Background(), fixtureDDL); err != nil {
		t.Fatalf("create fixture schema: %v", err)
	}
	return pool
}

func TestIntrospectionMatchesTheFixture(t *testing.T) {
	ctx := context.Background()
	pool := Pool(t)

	res, err := introspect.Table(ctx, pool, "pgsheet_test", "customers")
	if err != nil {
		t.Fatalf("Table: %v", err)
	}

	byName := map[string]int{}
	for i, c := range res.Schema.Columns {
		byName[c.Name] = i
	}

	t.Run("identity kinds are distinguished", func(t *testing.T) {
		id := res.Schema.Columns[byName["id"]]
		if id.IdentityKind != "BY DEFAULT" {
			t.Errorf("id identity = %q, want BY DEFAULT", id.IdentityKind)
		}
		if !id.AcceptsValue() {
			t.Error("a BY DEFAULT identity must be mappable")
		}

		ref := res.Schema.Columns[byName["ref"]]
		if ref.IdentityKind != "ALWAYS" {
			t.Errorf("ref identity = %q, want ALWAYS", ref.IdentityKind)
		}
		if ref.AcceptsValue() {
			t.Error("a GENERATED ALWAYS identity must be refused (E103)")
		}
	})

	t.Run("generated columns are refused", func(t *testing.T) {
		c := res.Schema.Columns[byName["display_name"]]
		if !c.IsGenerated {
			t.Error("display_name was not detected as generated")
		}
		if c.AcceptsValue() {
			t.Error("a stored generated column must be refused (E103)")
		}
	})

	t.Run("enum labels are read in declaration order", func(t *testing.T) {
		c := res.Schema.Columns[byName["status"]]
		want := []string{"active", "inactive", "suspended"}
		if len(c.EnumValues) != len(want) {
			t.Fatalf("enum values = %v, want %v", c.EnumValues, want)
		}
		for i := range want {
			if c.EnumValues[i] != want[i] {
				t.Errorf("enum[%d] = %q, want %q", i, c.EnumValues[i], want[i])
			}
		}
		if c.EnumSchema != "pgsheet_test" {
			t.Errorf("enum schema = %q, want pgsheet_test — the cast has to be qualified", c.EnumSchema)
		}
	})

	t.Run("length and precision", func(t *testing.T) {
		name := res.Schema.Columns[byName["name"]]
		if name.MaxLength == nil || *name.MaxLength != 255 {
			t.Errorf("name max length = %v, want 255", name.MaxLength)
		}
		credit := res.Schema.Columns[byName["credit_limit"]]
		if credit.NumericPrecision == nil || *credit.NumericPrecision != 12 {
			t.Errorf("credit precision = %v, want 12", credit.NumericPrecision)
		}
		if credit.NumericScale == nil || *credit.NumericScale != 2 {
			t.Errorf("credit scale = %v, want 2", credit.NumericScale)
		}
	})

	t.Run("required columns", func(t *testing.T) {
		if !res.Schema.Columns[byName["name"]].Required() {
			t.Error("name is NOT NULL with no default and should be required")
		}
		// status is NOT NULL but has a default, so the database can fill it.
		if res.Schema.Columns[byName["status"]].Required() {
			t.Error("status has a default and should not be reported as required")
		}
	})

	t.Run("primary key and its sequence", func(t *testing.T) {
		if res.Schema.PrimaryKey == nil {
			t.Fatal("no primary key found")
		}
		if len(res.Schema.PrimaryKey.Columns) != 1 || res.Schema.PrimaryKey.Columns[0] != "id" {
			t.Errorf("primary key = %v, want [id]", res.Schema.PrimaryKey.Columns)
		}
		if res.Schema.PKSequence == nil {
			t.Fatal("the identity column's sequence was not resolved")
		}
		if res.Schema.PKSequence.NextValue < 1 {
			t.Errorf("next value = %d, want a positive estimate", res.Schema.PKSequence.NextValue)
		}
	})

	t.Run("partial unique index is flagged", func(t *testing.T) {
		found := false
		for _, ix := range res.UniqueIndexes {
			if ix.Name == "customers_active_phone" {
				found = true
				if !ix.Partial {
					t.Error("a WHERE-clause index must be marked partial: it cannot be checked offline")
				}
			}
		}
		if !found {
			t.Error("the unique index with no constraint behind it was not found")
		}
	})

	t.Run("check constraints are all present", func(t *testing.T) {
		want := map[string]bool{
			"customers_score_range":     false,
			"customers_credit_positive": false,
			"customers_email_shape":     false,
			"customers_code_len":        false,
		}
		for _, c := range res.Schema.Constraints {
			if _, ok := want[c.Name]; ok {
				want[c.Name] = true
			}
		}
		for name, seen := range want {
			if !seen {
				t.Errorf("constraint %s was not read", name)
			}
		}
	})
}

func TestCompositePrimaryKey(t *testing.T) {
	ctx := context.Background()
	pool := Pool(t)

	res, err := introspect.Table(ctx, pool, "pgsheet_test", "orders")
	if err != nil {
		t.Fatalf("Table: %v", err)
	}

	if res.Schema.PrimaryKey == nil {
		t.Fatal("no primary key found")
	}
	if len(res.Schema.PrimaryKey.Columns) != 2 {
		t.Fatalf("primary key = %v, want two columns in order", res.Schema.PrimaryKey.Columns)
	}
	if res.Schema.PrimaryKey.Columns[0] != "customer_id" || res.Schema.PrimaryKey.Columns[1] != "line_no" {
		t.Errorf("primary key = %v, want [customer_id line_no]", res.Schema.PrimaryKey.Columns)
	}
	// A composite key has no sequence, so the sequence strategy is unavailable.
	if res.Schema.PKSequence != nil {
		t.Errorf("composite key reported a sequence: %+v", res.Schema.PKSequence)
	}

	foundFK := false
	for _, c := range res.Schema.Constraints {
		if c.Type == "f" {
			foundFK = true
			if c.RefTable != "pgsheet_test.customers" {
				t.Errorf("foreign key references %q, want pgsheet_test.customers", c.RefTable)
			}
		}
	}
	if !foundFK {
		t.Error("the foreign key was not read")
	}
}

func TestNaturalKeyHasNoSequence(t *testing.T) {
	ctx := context.Background()
	pool := Pool(t)

	res, err := introspect.Table(ctx, pool, "pgsheet_test", "legacy")
	if err != nil {
		t.Fatalf("Table: %v", err)
	}
	if res.Schema.PKSequence != nil {
		t.Errorf("a text primary key reported a sequence: %+v", res.Schema.PKSequence)
	}
}

// Reading the sequence must not consume a value: an operator who opens the
// primary key screen and then cancels must leave no gap in the ids (spec §6.5).
func TestReadingTheSequenceConsumesNothing(t *testing.T) {
	ctx := context.Background()
	pool := Pool(t)

	before := sequenceLastValue(t, pool)

	for i := 0; i < 5; i++ {
		if _, err := introspect.Table(ctx, pool, "pgsheet_test", "customers"); err != nil {
			t.Fatalf("Table: %v", err)
		}
	}

	if after := sequenceLastValue(t, pool); after != before {
		t.Errorf("the sequence moved from %v to %v just from being read", before, after)
	}
}

func sequenceLastValue(t *testing.T, pool *pgxpool.Pool) any {
	t.Helper()

	var last any
	err := pool.QueryRow(context.Background(), `
		SELECT last_value FROM pg_sequences
		WHERE schemaname = 'pgsheet_test' AND sequencename LIKE 'customers_id_%'`).Scan(&last)
	if err != nil {
		t.Skipf("sequence state unavailable: %v", err)
	}
	return last
}

func TestListTablesSeesTheFixture(t *testing.T) {
	ctx := context.Background()
	pool := Pool(t)

	tables, err := introspect.ListTables(ctx, pool)
	if err != nil {
		t.Fatalf("ListTables: %v", err)
	}

	found := map[string]bool{}
	for _, tr := range tables {
		if tr.Schema == "pgsheet_test" {
			found[tr.Table] = true
		}
	}
	for _, want := range []string{"customers", "orders", "legacy"} {
		if !found[want] {
			t.Errorf("%s was not listed", want)
		}
	}
}
