package app

import (
	"strings"
	"testing"

	"pgsheet/internal/domain"
)

func schemaWithKey(keyColumns []string, columns ...domain.Column) domain.TableSchema {
	pk := domain.Constraint{Name: "t_pkey", Type: "p", Columns: keyColumns}
	return domain.TableSchema{
		Schema:      "public",
		Table:       "t",
		Columns:     columns,
		Constraints: []domain.Constraint{pk},
		PrimaryKey:  &pk,
	}
}

func optionFor(options []PKOption, strategy domain.PKStrategy) PKOption {
	for _, o := range options {
		if o.Strategy == strategy {
			return o
		}
	}
	return PKOption{}
}

// A sequence is not the only way a database fills a key. Spec §10 branches on
// "identity or nextval default", which reads as though a sequence were the
// only mechanism; a uuid key with DEFAULT gen_random_uuid() is generated by
// the database with no sequence anywhere, and treating it as a natural key
// would make the operator invent values the database was going to produce.
func TestDatabaseSuppliesKey(t *testing.T) {
	tests := []struct {
		name   string
		schema domain.TableSchema
		want   bool
	}{
		{
			name: "identity",
			schema: schemaWithKey([]string{"id"},
				domain.Column{Name: "id", DataType: "int4", IsIdentity: true, IdentityKind: "BY DEFAULT", HasDefault: true}),
			want: true,
		},
		{
			name: "serial with a nextval default",
			schema: schemaWithKey([]string{"id"},
				domain.Column{Name: "id", DataType: "int4", HasDefault: true, DefaultExpr: "nextval('t_id_seq'::regclass)"}),
			want: true,
		},
		{
			name: "uuid with a generated default and no sequence",
			schema: schemaWithKey([]string{"id"},
				domain.Column{Name: "id", DataType: "uuid", HasDefault: true, DefaultExpr: "gen_random_uuid()"}),
			want: true,
		},
		{
			name: "natural text key",
			schema: schemaWithKey([]string{"code"},
				domain.Column{Name: "code", DataType: "text"}),
			want: false,
		},
		{
			name: "composite where every part has a default",
			schema: schemaWithKey([]string{"a", "b"},
				domain.Column{Name: "a", DataType: "uuid", HasDefault: true, DefaultExpr: "gen_random_uuid()"},
				domain.Column{Name: "b", DataType: "int4", HasDefault: true, DefaultExpr: "1"}),
			want: true,
		},
		{
			name: "composite where one part is natural",
			schema: schemaWithKey([]string{"a", "b"},
				domain.Column{Name: "a", DataType: "uuid", HasDefault: true, DefaultExpr: "gen_random_uuid()"},
				domain.Column{Name: "b", DataType: "int4"}),
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := databaseSuppliesKey(tt.schema); got != tt.want {
				t.Errorf("databaseSuppliesKey = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestPKOptionsOfferGenerationForAUUIDKey(t *testing.T) {
	schema := schemaWithKey([]string{"id"},
		domain.Column{Name: "id", DataType: "uuid", HasDefault: true, DefaultExpr: "gen_random_uuid()"},
		domain.Column{Name: "name", DataType: "text"})

	options := pkOptions(schema)
	generate := optionFor(options, domain.PKSequence)

	if !generate.Available {
		t.Fatalf("a uuid key with a default must be offered as database-assigned; reason given: %q", generate.Reason)
	}
	if !generate.Recommended {
		t.Error("letting the database assign the key is the safe default and should be recommended")
	}
	// With no sequence there is no next value to quote, so the option has to
	// say what the database will actually run instead.
	if !strings.Contains(generate.Description, "gen_random_uuid()") {
		t.Errorf("the option does not say how the key is assigned: %q", generate.Description)
	}

	if choice := defaultPKChoice(schema); choice.Strategy != domain.PKSequence {
		t.Errorf("default strategy = %q, want the database to assign it", choice.Strategy)
	}
}

func TestPKOptionsRefuseGenerationForANaturalKey(t *testing.T) {
	schema := schemaWithKey([]string{"code"},
		domain.Column{Name: "code", DataType: "text"},
		domain.Column{Name: "label", DataType: "text"})

	generate := optionFor(pkOptions(schema), domain.PKSequence)

	if generate.Available {
		t.Error("a key with no identity and no default cannot be assigned by the database")
	}
	if generate.Reason == "" {
		t.Error("an unavailable option must say why")
	}

	if choice := defaultPKChoice(schema); choice.Strategy != domain.PKMapped {
		t.Errorf("default strategy = %q, want the values to come from the sheet", choice.Strategy)
	}
}

func TestPKOptionsQuoteTheSequenceEstimateWhenThereIsOne(t *testing.T) {
	schema := schemaWithKey([]string{"id"},
		domain.Column{Name: "id", DataType: "int4", IsIdentity: true, IdentityKind: "BY DEFAULT", HasDefault: true})
	schema.PKSequence = &domain.Sequence{Name: "public.t_id_seq", NextValue: 1247, Increment: 1, IsCalled: true}

	generate := optionFor(pkOptions(schema), domain.PKSequence)

	if !strings.Contains(generate.Description, "1247") {
		t.Errorf("the estimate is not shown: %q", generate.Description)
	}
	// It must be described as an estimate: reading the sequence reserves
	// nothing, and rows may be added before the file runs (spec §6.5).
	if !strings.Contains(generate.Description, "estimate") {
		t.Errorf("the next value must be labelled an estimate: %q", generate.Description)
	}
}

func TestDescribePKNamesTheMechanism(t *testing.T) {
	uuidSchema := schemaWithKey([]string{"id"},
		domain.Column{Name: "id", DataType: "uuid", HasDefault: true, DefaultExpr: "gen_random_uuid()"})

	got := describePK(uuidSchema, PKChoice{Strategy: domain.PKSequence})
	if !strings.Contains(got, "gen_random_uuid()") {
		t.Errorf("the .sql header should record how the key was assigned, got %q", got)
	}
}

func TestNoPrimaryKeyOffersOnlyTheNoneStrategy(t *testing.T) {
	schema := domain.TableSchema{
		Schema:  "public",
		Table:   "t",
		Columns: []domain.Column{{Name: "a", DataType: "text"}},
	}

	options := pkOptions(schema)
	if len(options) != 1 || options[0].Strategy != domain.PKNone {
		t.Fatalf("options = %+v, want only the none strategy", options)
	}
	if choice := defaultPKChoice(schema); choice.Strategy != domain.PKNone {
		t.Errorf("default strategy = %q, want none", choice.Strategy)
	}
}
