//go:build integration

// End-to-end tests against a real PostgreSQL server (spec §16).
//
// See internal/introspect/integration_test.go for how to run these and why
// they take a DSN rather than starting a container themselves.
package validator_test

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/xuri/excelize/v2"

	"pgsheet/internal/dbconn"
	"pgsheet/internal/domain"
	"pgsheet/internal/excel"
	"pgsheet/internal/introspect"
	"pgsheet/internal/mapper"
	"pgsheet/internal/sqlgen"
	"pgsheet/internal/validator"
)

const roundTripDDL = `
DROP SCHEMA IF EXISTS pgsheet_rt CASCADE;
CREATE SCHEMA pgsheet_rt;

CREATE TYPE pgsheet_rt.customer_status AS ENUM ('active', 'inactive');

CREATE TABLE pgsheet_rt.regions (
    code text PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO pgsheet_rt.regions VALUES ('BEY', 'Beirut'), ('TRP', 'Tripoli');

CREATE TABLE pgsheet_rt.customers (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    email        varchar(255) NOT NULL UNIQUE,
    status       pgsheet_rt.customer_status NOT NULL,
    credit_limit numeric(12,2),
    signup_date  date,
    seen_at      timestamptz,
    notes        text,
    region       text REFERENCES pgsheet_rt.regions(code)
);
`

func integrationPool(t *testing.T) (*pgxpool.Pool, dbconn.ServerInfo) {
	t.Helper()

	dsn := os.Getenv("PGSHEET_TEST_DSN")
	if dsn == "" {
		t.Skip("set PGSHEET_TEST_DSN to run the integration tests")
	}

	pool, err := pgxpool.New(context.Background(), dsn)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	t.Cleanup(pool.Close)

	if _, err := pool.Exec(context.Background(), roundTripDDL); err != nil {
		t.Fatalf("create schema: %v", err)
	}

	info, err := dbconn.Probe(context.Background(), pool)
	if err != nil {
		t.Fatalf("probe: %v", err)
	}
	return pool, info
}

func roundTripWorkbook(t *testing.T) string {
	t.Helper()

	f := excelize.NewFile()
	defer f.Close()

	const sheet = "Sheet1"
	headers := []string{"Name", "Email", "Status", "Credit", "Signup", "Seen", "Notes"}
	for i, h := range headers {
		cell, _ := excelize.CoordinatesToCellName(i+1, 1)
		if err := f.SetCellStr(sheet, cell, h); err != nil {
			t.Fatal(err)
		}
	}

	dateStyle, err := f.NewStyle(&excelize.Style{NumFmt: 14})
	if err != nil {
		t.Fatal(err)
	}

	rows := [][]string{
		{"Acme SARL", "contact@acme.lb", "active", "15000.00", "", "2024-03-15 14:22:00", ""},
		{"O'Brien & Sons", "hello@obrien.ie", "active", "2500.50", "", "", "Pays in EUR"},
		{"Zeta \\ Partners", "z@zeta.example", "inactive", "0.00", "", "", "Backslash and 'quotes'"},
	}
	for r, row := range rows {
		for c, v := range row {
			cell, _ := excelize.CoordinatesToCellName(c+1, r+2)
			if err := f.SetCellStr(sheet, cell, v); err != nil {
				t.Fatal(err)
			}
		}
		// A real date cell in the Signup column.
		cell, _ := excelize.CoordinatesToCellName(5, r+2)
		if err := f.SetCellValue(sheet, cell, time.Date(2024, 3, 15, 0, 0, 0, 0, time.UTC)); err != nil {
			t.Fatal(err)
		}
		if err := f.SetCellStyle(sheet, cell, cell, dateStyle); err != nil {
			t.Fatal(err)
		}
	}

	path := filepath.Join(t.TempDir(), "roundtrip.xlsx")
	if err := f.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	return path
}

func roundTripMappings() []domain.ColumnMapping {
	tr := domain.Transform{Trim: true, BlankAsNull: true}
	return []domain.ColumnMapping{
		{ExcelColumn: "Name", ExcelIndex: 0, DBColumn: "name", Enabled: true, Transform: domain.Transform{Trim: true}},
		{ExcelColumn: "Email", ExcelIndex: 1, DBColumn: "email", Enabled: true, Transform: domain.Transform{Trim: true}},
		{ExcelColumn: "Status", ExcelIndex: 2, DBColumn: "status", Enabled: true, Transform: domain.Transform{Trim: true}},
		{ExcelColumn: "Credit", ExcelIndex: 3, DBColumn: "credit_limit", Enabled: true, Transform: tr},
		{ExcelColumn: "Signup", ExcelIndex: 4, DBColumn: "signup_date", Enabled: true, Transform: tr},
		{ExcelColumn: "Seen", ExcelIndex: 5, DBColumn: "seen_at", Enabled: true, Transform: tr},
		{ExcelColumn: "Notes", ExcelIndex: 6, DBColumn: "notes", Enabled: true, Transform: tr},
	}
}

// setup returns everything a round trip needs.
func setup(t *testing.T) (context.Context, *pgxpool.Pool, dbconn.ServerInfo, *excel.Workbook, domain.SheetInfo, introspect.Result, mapper.Plan, validator.Options) {
	t.Helper()

	ctx := context.Background()
	pool, info := integrationPool(t)

	res, err := introspect.Table(ctx, pool, "pgsheet_rt", "customers")
	if err != nil {
		t.Fatalf("introspect: %v", err)
	}

	wb, err := excel.Open(roundTripWorkbook(t))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = wb.Close() })

	sheet, err := wb.Describe(ctx, "Sheet1", 1)
	if err != nil {
		t.Fatal(err)
	}

	plan := mapper.BuildPlan(roundTripMappings(), res.Schema, domain.PKSequence)
	opts := validator.Options{
		StandardConformingStrings: info.StandardConformingStrings,
		SourceTimezone:            time.UTC,
	}
	return ctx, pool, info, wb, sheet, res, plan, opts
}

// The full promise: generate a file, run it, read the rows back, and find what
// the spreadsheet said — quotes, backslashes, decimals and all.
func TestGeneratedFileExecutesAndRoundTrips(t *testing.T) {
	ctx, pool, _, wb, sheet, res, plan, opts := setup(t)

	rep, err := validator.Run(ctx, validator.Input{
		Workbook: wb, Sheet: sheet, Mappings: roundTripMappings(), Plan: plan,
		Introspection: res, Pool: pool, Opts: opts,
		Settings: validator.Settings{MaxIssues: 1000, ColumnMisalignThreshold: 0.3, CheckUniqueAgainstDB: true, SkipBlankRows: true},
	})
	if err != nil {
		t.Fatalf("validate: %v", err)
	}
	if !rep.OK() {
		t.Fatalf("the fixture should validate cleanly: %+v", rep.Issues)
	}

	var buf bytes.Buffer
	if _, err := sqlgen.Generate(ctx, &buf, sqlgen.Input{
		Workbook: wb, SheetName: sheet.Name, DataStart: sheet.DataStart,
		Target: sqlgen.Target{
			Schema: res.Schema.Schema, Table: res.Schema.Table,
			Columns: validator.PlanColumnNames(plan),
		},
		Coerce:  validator.RowLiterals(plan, opts, true),
		Options: sqlgen.Options{Mode: sqlgen.ModeInsert, BatchSize: 500, WrapInTransaction: true},
	}); err != nil {
		t.Fatalf("generate: %v", err)
	}

	// Run the generated file exactly as an operator would.
	if _, err := pool.Exec(ctx, buf.String()); err != nil {
		t.Fatalf("the generated file did not execute: %v\n%s", err, buf.String())
	}

	var count int
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM pgsheet_rt.customers`).Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 3 {
		t.Fatalf("inserted %d rows, want 3", count)
	}

	var name, notes string
	if err := pool.QueryRow(ctx, `
		SELECT name, notes FROM pgsheet_rt.customers WHERE email = 'z@zeta.example'`).
		Scan(&name, &notes); err != nil {
		t.Fatal(err)
	}
	if name != `Zeta \ Partners` {
		t.Errorf("name round-tripped as %q, want the backslash intact", name)
	}
	if notes != "Backslash and 'quotes'" {
		t.Errorf("notes round-tripped as %q", notes)
	}

	var credit string
	if err := pool.QueryRow(ctx, `
		SELECT credit_limit::text FROM pgsheet_rt.customers WHERE email = 'hello@obrien.ie'`).
		Scan(&credit); err != nil {
		t.Fatal(err)
	}
	if credit != "2500.50" {
		t.Errorf("credit_limit = %s, want 2500.50 exactly", credit)
	}
}

// The dry run must leave nothing behind, whether it passes or fails.
func TestDryRunRollsBack(t *testing.T) {
	ctx, pool, _, wb, sheet, _, plan, opts := setup(t)

	rep, err := validator.DryRun(ctx, validator.DryRunInput{
		Pool: pool, Workbook: wb, SheetName: sheet.Name, DataStart: sheet.DataStart,
		Plan: plan, Opts: opts, MaxIssues: 100, SkipBlank: true,
	})
	if err != nil {
		t.Fatalf("dry run: %v", err)
	}
	if !rep.OK() {
		t.Fatalf("the fixture should pass the dry run: %+v", rep.Issues)
	}

	var count int
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM pgsheet_rt.customers`).Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 0 {
		t.Fatalf("the dry run left %d rows behind — it must always roll back", count)
	}
}

// A constraint violation has to come back with the row that caused it.
func TestDryRunReportsAViolationAndStillRollsBack(t *testing.T) {
	ctx, pool, _, wb, sheet, _, plan, opts := setup(t)

	// Put one of the emails in the table first, so the file collides with it.
	if _, err := pool.Exec(ctx, `
		INSERT INTO pgsheet_rt.customers (name, email, status)
		VALUES ('Existing', 'contact@acme.lb', 'active')`); err != nil {
		t.Fatal(err)
	}

	rep, err := validator.DryRun(ctx, validator.DryRunInput{
		Pool: pool, Workbook: wb, SheetName: sheet.Name, DataStart: sheet.DataStart,
		Plan: plan, Opts: opts, MaxIssues: 100, SkipBlank: true,
	})
	if err != nil {
		t.Fatalf("dry run: %v", err)
	}
	if rep.OK() {
		t.Fatal("the duplicate email should have failed the dry run")
	}

	found := false
	for _, i := range rep.Issues {
		if i.Code == "E304" || i.Code == "E302" {
			found = true
			if i.ExcelRow == 0 {
				t.Errorf("the violation has no row: %+v", i)
			}
		}
	}
	if !found {
		t.Errorf("expected a uniqueness violation, got %+v", rep.Issues)
	}

	var count int
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM pgsheet_rt.customers`).Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 1 {
		t.Fatalf("the table holds %d rows, want only the one inserted by this test", count)
	}
}

// After explicit key values, the next ordinary insert must still work. This is
// the failure that setval exists to prevent (spec §10).
func TestSetvalLeavesTheSequenceUsable(t *testing.T) {
	ctx, pool, _, _, _, _, _, _ := setup(t)

	// Insert a row with an explicit id well past the sequence's position, the
	// way a PKMapped file does.
	if _, err := pool.Exec(ctx, `
		INSERT INTO pgsheet_rt.customers (id, name, email, status)
		VALUES (500, 'Explicit', 'explicit@example.com', 'active')`); err != nil {
		t.Fatal(err)
	}

	// Without the resynchronisation the next insert collides.
	if _, err := pool.Exec(ctx, `
		SELECT setval(pg_get_serial_sequence('pgsheet_rt.customers', 'id'),
		              (SELECT COALESCE(MAX(id), 1) FROM pgsheet_rt.customers), true)`); err != nil {
		t.Fatalf("setval: %v", err)
	}

	if _, err := pool.Exec(ctx, `
		INSERT INTO pgsheet_rt.customers (name, email, status)
		VALUES ('Next', 'next@example.com', 'active')`); err != nil {
		t.Fatalf("the insert after setval failed, which is exactly what setval prevents: %v", err)
	}
}

// A timestamptz literal carries an explicit offset, so the same file means the
// same instant regardless of the server's TimeZone setting (spec §11, §16).
func TestTimestamptzSurvivesDifferentServerTimezones(t *testing.T) {
	ctx, pool, info, wb, sheet, res, plan, _ := setup(t) //nolint:dogsled

	beirut, err := time.LoadLocation("Asia/Beirut")
	if err != nil {
		t.Skip("timezone database unavailable")
	}
	opts := validator.Options{
		StandardConformingStrings: info.StandardConformingStrings,
		SourceTimezone:            beirut,
	}

	var buf bytes.Buffer
	if _, err := sqlgen.Generate(ctx, &buf, sqlgen.Input{
		Workbook: wb, SheetName: sheet.Name, DataStart: sheet.DataStart,
		Target: sqlgen.Target{
			Schema: res.Schema.Schema, Table: res.Schema.Table,
			Columns: validator.PlanColumnNames(plan),
		},
		Coerce:  validator.RowLiterals(plan, opts, true),
		Options: sqlgen.Options{Mode: sqlgen.ModeInsert, BatchSize: 500, WrapInTransaction: true},
	}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	script := buf.String()

	var reference time.Time
	for i, tz := range []string{"UTC", "Asia/Beirut", "America/New_York"} {
		if _, err := pool.Exec(ctx, `TRUNCATE pgsheet_rt.customers`); err != nil {
			t.Fatal(err)
		}
		if _, err := pool.Exec(ctx, `SET TIME ZONE `+quoteTZ(tz)); err != nil {
			t.Fatal(err)
		}
		if _, err := pool.Exec(ctx, script); err != nil {
			t.Fatalf("running under %s: %v", tz, err)
		}

		var seen time.Time
		if err := pool.QueryRow(ctx, `
			SELECT seen_at FROM pgsheet_rt.customers WHERE email = 'contact@acme.lb'`).Scan(&seen); err != nil {
			t.Fatal(err)
		}

		if i == 0 {
			reference = seen
			continue
		}
		if !seen.Equal(reference) {
			t.Errorf("under %s the value is %s, but under UTC it was %s — the same file must mean the same instant",
				tz, seen.UTC(), reference.UTC())
		}
	}

	if _, err := pool.Exec(ctx, `SET TIME ZONE 'UTC'`); err != nil {
		t.Fatal(err)
	}
}

func quoteTZ(tz string) string {
	return "'" + tz + "'"
}

// Foreign key checking is opt-in and, until this runs, has never touched a
// database. It reports a mapped value with no matching row in the referenced
// table, with the row it came from.
func TestForeignKeyCheckFindsAMissingReference(t *testing.T) {
	ctx, pool, info, _, _, res, _, _ := setup(t)

	path := buildSheetWithRegions(t, [][]string{
		{"Acme SARL", "a@example.com", "active", "BEY"},
		{"Beta Ltd", "b@example.com", "active", "NOPE"},
	})

	wb, err := excel.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer wb.Close()

	sheet, err := wb.Describe(ctx, "Sheet1", 1)
	if err != nil {
		t.Fatal(err)
	}

	tr := domain.Transform{Trim: true}
	mappings := []domain.ColumnMapping{
		{ExcelColumn: "Name", ExcelIndex: 0, DBColumn: "name", Enabled: true, Transform: tr},
		{ExcelColumn: "Email", ExcelIndex: 1, DBColumn: "email", Enabled: true, Transform: tr},
		{ExcelColumn: "Status", ExcelIndex: 2, DBColumn: "status", Enabled: true, Transform: tr},
		{ExcelColumn: "Region", ExcelIndex: 3, DBColumn: "region", Enabled: true, Transform: tr},
	}

	rep, err := validator.Run(ctx, validator.Input{
		Workbook:      wb,
		Sheet:         sheet,
		Mappings:      mappings,
		Plan:          mapper.BuildPlan(mappings, res.Schema, domain.PKSequence),
		Introspection: res,
		Pool:          pool,
		Opts: validator.Options{
			StandardConformingStrings: info.StandardConformingStrings,
			SourceTimezone:            time.UTC,
		},
		Settings: validator.Settings{
			MaxIssues:               1000,
			ColumnMisalignThreshold: 0.3,
			CheckForeignKeys:        true,
			SkipBlankRows:           true,
		},
	})
	if err != nil {
		t.Fatalf("validate: %v", err)
	}

	var found *validator.Issue
	for i := range rep.Issues {
		if rep.Issues[i].Code == "E305" {
			found = &rep.Issues[i]
		}
	}
	if found == nil {
		t.Fatalf("expected E305 for the missing region, got %+v", rep.Issues)
	}
	if found.ExcelRow != 3 {
		t.Errorf("reported row %d, want row 3", found.ExcelRow)
	}
	if !strings.Contains(found.Value, "NOPE") {
		t.Errorf("the issue does not quote the offending value: %+v", found)
	}

	// The row whose region exists must not be reported.
	for _, i := range rep.Issues {
		if i.Code == "E305" && i.ExcelRow == 2 {
			t.Errorf("row 2 references BEY, which exists, but was reported: %+v", i)
		}
	}
}

func buildSheetWithRegions(t *testing.T, rows [][]string) string {
	t.Helper()

	f := excelize.NewFile()
	defer f.Close()

	const sheet = "Sheet1"
	for i, h := range []string{"Name", "Email", "Status", "Region"} {
		cell, _ := excelize.CoordinatesToCellName(i+1, 1)
		if err := f.SetCellStr(sheet, cell, h); err != nil {
			t.Fatal(err)
		}
	}
	for r, row := range rows {
		for c, v := range row {
			cell, _ := excelize.CoordinatesToCellName(c+1, r+2)
			if err := f.SetCellStr(sheet, cell, v); err != nil {
				t.Fatal(err)
			}
		}
	}

	path := filepath.Join(t.TempDir(), "regions.xlsx")
	if err := f.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	return path
}
